# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergo" do
  version "6.0.5"

  on_macos do
    on_arm do
      sha256 "c314104bba9a3bd4868a58736c11f38ae615568d3d696e2e43044b222c9a6193"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "401d4d2e739e8b903fc6f15fa305eae0d0ff59801ad1e3ea5f2d922ded0bca8e"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "29d087e421a9d49aaf88b1543448f2f9498ca520e3d18f2b6110131f59271c7d"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7fe19c2c1cbdd679287dbb34153ad014186446232978d2a14ab739a31e86546a"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergo"
  desc "Local, dependency-aware backlog for coding agents"
  homepage "https://github.com/sandover/ergo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergo"]
    end
  end

  # No zap stanza required
end
