# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergo" do
  version "4.3.1"

  on_macos do
    on_intel do
      sha256 "2db0fafb635ae8e4a591ab2b9089f39f815ef55767ae3690fea3b6bcf9b7a115"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "919d9bec8132db9b511b851c606424a1bb17cc3010f32bbbc2b524d5dd1da6a7"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05d8811b845df1291b0474a5e2d1bd4fbcaf4f4f949b15d3924a5777fb852e7c"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0ac7500e9d1b08fa7f9778b420bcc9b8905d0ce7a043c760c7878bafad8e45e"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ergo"
  desc "Local, dependency-aware backlog for coding agents"
  homepage "https://github.com/sandover/ergo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergo"]
    end
  end

  # No zap stanza required

end
