# This file was generated by GoReleaser. DO NOT EDIT.
cask "ergo" do
  version "6.0.3"

  on_macos do
    on_arm do
      sha256 "40cfae7b24918a9210a43cf35cbeb2fb280cbda2379025542b2c90a668426d10"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ed50a16227b1833eb650fe915cdc194576caa91a9c054949f9b2143cc1aa457"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ecbc02cafab028e9836042292d10e3808a39832b03ead7c62ec042c66376129"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de37e953298e589425cff651720cf91a96d896360fdf94c2e9f2aeee169d55e6"
      url "https://github.com/sandover/ergo/releases/download/v#{version}/ergo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ergo"
  desc "Local, dependency-aware backlog for coding agents"
  homepage "https://github.com/sandover/ergo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ergo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ergo"]
    end
  end

  # No zap stanza required
end
