# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ergo < Formula
  desc "Minimal multi-agent DAG task planner built on an append-only JSONL event log"
  homepage "https://github.com/sandover/ergo"
  version "0.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandover/ergo/releases/download/v0.5.5/ergo_0.5.5_darwin_amd64.tar.gz"
      sha256 "35caa7a7dbb8935a0dd190a94750cf4a6cdc3c5c636957f61f69ac5d92e66477"

      def install
        bin.install "ergo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandover/ergo/releases/download/v0.5.5/ergo_0.5.5_darwin_arm64.tar.gz"
      sha256 "ceaa6d2f34025929e9b2096e0c319757b3413410b92eade338383936f2c2b1ba"

      def install
        bin.install "ergo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandover/ergo/releases/download/v0.5.5/ergo_0.5.5_linux_amd64.tar.gz"
      sha256 "a173907dbfbd24d2d2b5619294832ea3de841a3fc0d8d196bc9258de33d8439c"
      def install
        bin.install "ergo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandover/ergo/releases/download/v0.5.5/ergo_0.5.5_linux_arm64.tar.gz"
      sha256 "f3752b1fdf8866d80d4ba025e33cd349d1451e900f511e9387e5f1a17c9d3fe0"
      def install
        bin.install "ergo"
      end
    end
  end
end
