# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ergo < Formula
  desc "Minimal multi-agent DAG task planner built on an append-only JSONL event log"
  homepage "https://github.com/sandover/ergo"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandover/ergo/releases/download/v0.9.3/ergo_0.9.3_darwin_amd64.tar.gz"
      sha256 "36d38945882f9d1add9a1f7783935b520338a522130ffa7d3c626c40bfc88409"

      def install
        bin.install "ergo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandover/ergo/releases/download/v0.9.3/ergo_0.9.3_darwin_arm64.tar.gz"
      sha256 "74883cbc1ae4992f9dd562584db0cee7e000b10761b61753b2f81c2cea19b77b"

      def install
        bin.install "ergo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandover/ergo/releases/download/v0.9.3/ergo_0.9.3_linux_amd64.tar.gz"
      sha256 "9752aaf3a56ede2512b8e31549a5a9ea9a0a17a00d5d25e2061d78fff3ec9fcf"
      def install
        bin.install "ergo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandover/ergo/releases/download/v0.9.3/ergo_0.9.3_linux_arm64.tar.gz"
      sha256 "acf6d3e154c7c9d35e2dab46d94e4a90ee8baddbac42466da7210b7a9553dfe6"
      def install
        bin.install "ergo"
      end
    end
  end
end
